In [9]:
numbers = [10, 20, 30, 40, 50]
print("List:", numbers)

List: [10, 20, 30, 40, 50]


In [12]:
numbers = [10, 20, 30, 40, 50]
print("First element:", numbers[0])
print("Last element:", numbers[-1])

First element: 10
Last element: 50


In [13]:
numbers.append(60)  # Adds 60 to the end of the list
print("After append:", numbers)

numbers.insert(2, 25)  # Inserts 25 at index 2
print("After insert:", numbers)

After append: [10, 20, 30, 40, 50, 60]
After insert: [10, 20, 25, 30, 40, 50, 60]


In [14]:
numbers.remove(25)  # Removes the first occurrence of 25
print("After remove:", numbers)

numbers.pop(2)  # Removes the element at index 2
print("After pop:", numbers)

After remove: [10, 20, 30, 40, 50, 60]
After pop: [10, 20, 40, 50, 60]


In [5]:
for num in numbers:
    print("Number:", num)

Number: 10
Number: 20
Number: 40
Number: 50
Number: 60


In [6]:
import numpy as np

# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(matrix)

# Accessing elements in a 2D array
print("Element at row 1, column 2:", matrix[1][2])  # Output: 6

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6


In [ ]:
NPM = [2430506055, 2430506056, 2430506057, 2430506058, 2430506059]

print("NPM =", NPM)

NPM = [2430506055, 2430506056, 2430506057, 2430506058, 2430506059]


In [ ]:
NPM[1] = 243050605620

print("NPM =", NPM)

NPM = [2430506055, 243050605620, 2430506057, 2430506058, 2430506059]


In [ ]:
fakultas = ["FKIP", "TEKNIK", "FISIPOL", "FE", "FAPERTA"]

for range in fakultas:
  print("Fakultas: ", range)

Fakultas:  FKIP
Fakultas:  TEKNIK
Fakultas:  FISIPOL
Fakultas:  FE
Fakultas:  FAPERTA


In [ ]:
harga_barang = [10000, 30000, 50000, 75000, 85000]

print("Total harga barang:", sum(harga_barang))

Total harga barang: 250000


In [19]:
matriks = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

for baris in matriks:
  print(baris)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]


In [20]:
print("Element at fourth collumn and second row is: ", matriks[3][1])

Element at fourth collumn and second row is:  11


In [21]:
matriks.append(["09", "04", "20", "06"])

for baris in matriks:
  print(baris)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
['09', '04', '20', '06']


In [22]:
matriks[4].pop(2)

'20'

In [ ]:
for baris in matriks:
  print(baris)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[11, 12, 13]
['09', '04', '06']


In [23]:
matriks[4][2] = "14"

In [24]:
for baris in matriks:
  print(baris)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[10, 11, 12]
['09', '04', '14']


In [26]:
print("============================")
print("Welcome to the grocery store")
print("============================")
print("\n")

item = [
    "Trash Bag",
    "Chocolate",
    "Soft Drink"
]

for i in item:
  print(i)

print("\n")
print("=====================")
print("First Update Grocery Items")
print("=====================")
print("\n")

item.append("Ice Cream")

for i in item:
  print(i)

item.remove("Trash Bag")

print("\n")
print("=====================")
print("Second Update Grocery Items")
print("=====================")
print("\n")

for i in item:
  print(i)

Welcome to the grocery store


Trash Bag
Chocolate
Soft Drink


First Update Grocery Items


Trash Bag
Chocolate
Soft Drink
Ice Cream


Second Update Grocery Items


Chocolate
Soft Drink
Ice Cream


In [ ]:
size = 10

treasure_map = ["_" for _ in range(size)]

print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (0 hingga {size-1}).")

treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}) :"))
while treasure_index < 0 or treasure_index >= size:
    print("Lokasi tidak valid. Silakan coba lagi.")
    treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}) :"))

treasure_map[treasure_index] = "X"

def play_treasure_hunt():
  print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
  print("Cobalah untuk menemukan harta karun dengan menebak indeks yang benar.")

  while True:
    print("\nPeta saat ini: ", ["_" for _ in range(size)])

    try:
      guess = int(input(f"Masukkan indeks tebakanmu (0-{size-1}): "))
    except ValueError:
      print("Masukkan angka yang valid!")
      continue
    if guess < 0 or guess >= size:
      print("Indeks tidak valid, pilih anatara 0 hingga", size-1)
      continue
    if treasure_map[guess] == "X":
      print("Selamat! Kamu menemukan harta karun di lokasi:", guess)
      break
    else:
      print("Tidak ada harta di lokasi ini. Coba lagi!")

  print("Terima kasih sudah bermain!")

play_treasure_hunt()

Selamat datang di Treasure Hunt! Peta memiliki 10 lokasi (0 hingga 9).
Masukkan lokasi harta karun (0-9) :3

Harta Karun telah disembunyikan! Sekarang giliran pemain menebak.
Cobalah untuk menemukan harta karun dengan menebak indeks yang benar.

Peta saat ini:  ['_', '_', '_', '_', '_', '_', '_', '_', '_', '_']
Masukkan indeks tebakanmu (0-9): 1
Tidak ada harta di lokasi ini. Coba lagi!

Peta saat ini:  ['_', '_', '_', '_', '_', '_', '_', '_', '_', '_']
Masukkan indeks tebakanmu (0-9): 2
Tidak ada harta di lokasi ini. Coba lagi!

Peta saat ini:  ['_', '_', '_', '_', '_', '_', '_', '_', '_', '_']
Masukkan indeks tebakanmu (0-9): 3
Selamat! Kamu menemukan harta karun di lokasi: 3
Terima kasih sudah bermain!


In [ ]:
def play_treasure_hunt(size, treasure_map):
    print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
    while True:
        print("\nPeta saat ini:", ["_"] * size)
        guess = int(input(f"Masukkan indeks tebakanmu (0-{size-1}): "))
        if guess < 0 or guess >= size:
            print("Indeks tidak valid, pilih antara 0 hingga", size-1)
            continue
        if treasure_map[guess] == "X":
            print("Selamat! Kamu menemukan harta karun di lokasi:", guess)
            break
        else:
            print("Tidak ada harta di lokasi ini. Coba lagi!")
    print("Terima kasih sudah bermain!")

size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))
while size < 2:
    print("Ukuran peta harus minimal 2.")
    size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))

treasure_map = ["_"] * size
print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (0 hingga {size-1}).")

treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}): "))
while treasure_index < 0 or treasure_index >= size:
    print("Lokasi tidak valid. Silakan coba lagi.")
    treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}): "))

treasure_map[treasure_index] = "X"

play_treasure_hunt(size, treasure_map)


Masukkan ukuran peta yang diinginkan (minimal 2): 1
Ukuran peta harus minimal 2.
Masukkan ukuran peta yang diinginkan (minimal 2): 2
Selamat datang di Treasure Hunt! Peta memiliki 2 lokasi (0 hingga 1).
Masukkan lokasi harta karun (0-1): 1

Harta Karun telah disembunyikan! Sekarang giliran pemain menebak.

Peta saat ini: ['_', '_']
Masukkan indeks tebakanmu (0-1): 3
Indeks tidak valid, pilih antara 0 hingga 1

Peta saat ini: ['_', '_']
Masukkan indeks tebakanmu (0-1): 1
Selamat! Kamu menemukan harta karun di lokasi: 1
Terima kasih sudah bermain!


In [30]:
import random

def play_treasure_hunt(size, treasure_map):
    print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
    while True:
        print("\nPeta saat ini:", ["_"] * size)
        guess = int(input(f"Masukkan indeks tebakanmu (1-{size}): ")) - 1
        if guess < 0 or guess >= size:
            print("Indeks tidak valid, pilih antara 1 hingga", size)
            continue
        if treasure_map[guess] == "X":
            print("Selamat! Kamu menemukan harta karun di lokasi:", guess + 1)
            break
        else:
            print("Tidak ada harta di lokasi ini. Coba lagi!")
    print("Terima kasih sudah bermain!")

size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))
while size < 2:
    print("Ukuran peta harus minimal 2.")
    size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))

treasure_map = ["_"] * size
print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (1 hingga {size}).")

treasure_index = random.randint(0, size - 1)
print(f"Harta karun telah disembunyikan secara otomatis!")
8
treasure_map[treasure_index] = "X"

play_treasure_hunt(size, treasure_map)

Masukkan ukuran peta yang diinginkan (minimal 2): 4
Selamat datang di Treasure Hunt! Peta memiliki 4 lokasi (1 hingga 4).
Harta karun telah disembunyikan secara otomatis!

Harta Karun telah disembunyikan! Sekarang giliran pemain menebak.

Peta saat ini: ['_', '_', '_', '_']
Masukkan indeks tebakanmu (1-4): 1
Tidak ada harta di lokasi ini. Coba lagi!

Peta saat ini: ['_', '_', '_', '_']
Masukkan indeks tebakanmu (1-4): 2
Tidak ada harta di lokasi ini. Coba lagi!

Peta saat ini: ['_', '_', '_', '_']
Masukkan indeks tebakanmu (1-4): 3
Selamat! Kamu menemukan harta karun di lokasi: 3
Terima kasih sudah bermain!
